version: "3.9"
networks:
  my-network:
    name: commonspaces
    driver: bridge
    external: true
services:
  carbonneutral-shared-base:
    networks:
    - my-network
    volumes:
      - $APPDATA/Microsoft/UserSecrets/7bb1d295-54c5-4d09-9bd6-fa56fb74011b:/root/.microsoft/usersecrets/7bb1d295-54c5-4d09-9bd6-fa56fb74011b
      - $HOME/.microsoft/usersecrets/7bb1d295-54c5-4d09-9bd6-fa56fb74011b:/root/.microsoft/usersecrets/7bb1d295-54c5-4d09-9bd6-fa56fb74011b
    build:
      context: ./
      dockerfile: ./build/local-shared-base/Dockerfile    
    image: local:carbonneutral-shared-base
  id-carbonneutral:
    networks:
    - my-network
    volumes:
      - $APPDATA/Microsoft/UserSecrets/7bb1d295-54c5-4d09-9bd6-fa56fb74011b:/root/.microsoft/usersecrets/7bb1d295-54c5-4d09-9bd6-fa56fb74011b
      - $HOME/.microsoft/usersecrets/7bb1d295-54c5-4d09-9bd6-fa56fb74011b:/root/.microsoft/usersecrets/7bb1d295-54c5-4d09-9bd6-fa56fb74011b
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./src/++Identity/CarbonNeutral.Identity/src/CarbonNeutral.Identity.STS.Identity/Dockerfile
    ports:
      - "44320:44320"
    depends_on:
      - carbonneutral-shared-base
    environment:
      - VIRTUAL_HOST=wordsearchkingdom.com:44320
      - 'AdminConfiguration__IdentityAdminBaseUrl=https://id.wordsearchkingdom.com'
      - 'AdvancedConfiguration__IssuerUri=https://id.wordsearchkingdom.com'
      - DockerConfiguration__UpdateCaCertificate=true
      - ASPNETCORE_ENVIRONMENT=Development
  account-api-carbonneutral:
    networks:
    - my-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 10m
    volumes:
      - $APPDATA/Microsoft/UserSecrets/7bb1d295-54c5-4d09-9bd6-fa56fb74011b:/root/.microsoft/usersecrets/7bb1d295-54c5-4d09-9bd6-fa56fb74011b
      - $HOME/.microsoft/usersecrets/7bb1d295-54c5-4d09-9bd6-fa56fb74011b:/root/.microsoft/usersecrets/7bb1d295-54c5-4d09-9bd6-fa56fb74011b
    build:
      context: ./
      dockerfile: ./src/+Modules/Required/AccountModule/+Api/+AccountModuleApi/src/Dockerfile
    ports:
      - "5278:5278"
    depends_on:
      - carbonneutral-shared-base
      - id-carbonneutral
  liveroom-api-carbonneutral:
    networks:
    - my-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 10m
    volumes:
      - $APPDATA/Microsoft/UserSecrets/7bb1d295-54c5-4d09-9bd6-fa56fb74011b:/root/.microsoft/usersecrets/7bb1d295-54c5-4d09-9bd6-fa56fb74011b
      - $HOME/.microsoft/usersecrets/7bb1d295-54c5-4d09-9bd6-fa56fb74011b:/root/.microsoft/usersecrets/7bb1d295-54c5-4d09-9bd6-fa56fb74011b
    build:
      context: ./
      dockerfile: ./src/+Modules/Required/LiveRoomModule/+Api/+LiveRoomApi/src/Dockerfile
    ports:
      - "5292:5292"
    depends_on:
      - carbonneutral-shared-base
      - id-carbonneutral
  wsk-api-carbonneutral:
    networks:
    - my-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 10m
    volumes:
      - $APPDATA/Microsoft/UserSecrets/7bb1d295-54c5-4d09-9bd6-fa56fb74011b:/root/.microsoft/usersecrets/7bb1d295-54c5-4d09-9bd6-fa56fb74011b
      - $HOME/.microsoft/usersecrets/7bb1d295-54c5-4d09-9bd6-fa56fb74011b:/root/.microsoft/usersecrets/7bb1d295-54c5-4d09-9bd6-fa56fb74011b
    build:
      context: ./
      dockerfile: ./src/+Modules/Lazy/WordSearchKingdom/+Api/+WskApi/src/Dockerfile
    ports:
      - "5290:5290"
    depends_on:
      - carbonneutral-shared-base
      - id-carbonneutral
  wordsearchkingdom-blazor-client:
    networks:
    - my-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 10m
    build:
      context: ./
      dockerfile: ./src/UI/Client/CarbonNeutral.BlazorClient/src/Dockerfile
    ports:
      - "5020:5020"
      - "5021:5021"
    depends_on:
      - carbonneutral-shared-base
      - id-carbonneutral
      - account-api-carbonneutral
      - wsk-api-carbonneutral
  #wordsearchkingdom-blazor-reverse-proxy:
  #  restart: unless-stopped
  #  logging:
  #    driver: "json-file"
  #    options:
  #      max-file: 5
  #      max-size: 10m
  #  build:
  #    context: ./
  #    dockerfile: ./build/local-reverse-proxy/Dockerfile
  #  ports:
  #    - "80:80"
  #    - "443:443"
  #  depends_on:
  #    - carbonneutral-shared-base
  #    - id-carbonneutral
  #    - account-api-carbonneutral
  #    - wsk-api-carbonneutral
  #    - wordsearchkingdom-blazor-client
